"""Canonical sample instances covering the complete V1 contract registry."""

from energy_simlab.contracts.enums import (
    AcknowledgementReason,
    AcknowledgementStatus,
    AggregationKind,
    AlarmSeverity,
    AlarmTransition,
    BranchState,
    CommandAuthority,
    CommandKind,
    EnergizationState,
    EventPhase,
    FidelityResult,
    InterlockReason,
    OperatingMode,
    QualityReason,
    QualityValidity,
    SnapshotAction,
    TraceRecordKind,
    Unit,
)
from energy_simlab.contracts.records import (
    ActivePowerBalanceV1,
    AlarmEventV1,
    AlarmRuntimeSnapshotV1,
    AlarmStateV1,
    AcknowledgementV1,
    BessModelStateV1,
    BranchV1,
    BusV1,
    CommandReceiptV1,
    CommandV1,
    ConnectedComponentV1,
    ControllerSnapshotV1,
    FidelityEventV1,
    InterlockEventV1,
    MacroPublicationV1,
    ModelHandoffV1,
    ModelRegistrySnapshotV1,
    QualityV1,
    RngSnapshotV1,
    ScenarioV1,
    ScheduledEventSnapshotV1,
    SchedulerSnapshotV1,
    SimulationConfigV1,
    SnapshotEnvelopeV1,
    SnapshotLifecycleEventV1,
    SourceCounterV1,
    TelemetrySampleV1,
    TerminalV1,
    TopologyEventV1,
    TopologyRuntimeSnapshotV1,
    TopologySnapshotV1,
    TraceEntryV1,
    TraceV1,
    V1_DOMAIN_TYPES,
    VersionedV1,
)


def sample_records() -> tuple[VersionedV1, ...]:
    quality = QualityV1(
        validity=QualityValidity.GOOD,
        reason=QualityReason.NORMAL,
        detail="supported grid-connected calculation",
        origin_id="application",
        since_tick=0,
    )
    command = CommandV1(
        id="CMD-P-001",
        source_id="scenario",
        target_id="BESS",
        kind=CommandKind.SET_ACTIVE_POWER,
        authority=CommandAuthority.SCENARIO,
        logical_tick=0,
        sequence=1,
        apply_tick=10,
        expiry_tick=20,
        requested_value=0.4,
        unit=Unit.MEGAWATT,
        expected_model_version="1.0.0",
        expected_topology_version=0,
        reason="reference dispatch",
    )
    acknowledgement = AcknowledgementV1(
        id="ACK-CMD-P-001",
        source_id="command-validator",
        logical_tick=10,
        sequence=1,
        command_id=command.id,
        correlation_id=command.id,
        target_id="BESS",
        status=AcknowledgementStatus.ACCEPTED,
        reason=AcknowledgementReason.ACCEPTED,
        detail="request accepted",
        effective_tick=10,
        requested_value=0.4,
        accepted_value=0.4,
        unit=Unit.MEGAWATT,
        model_version="1.0.0",
        topology_version=0,
    )
    telemetry = TelemetrySampleV1(
        id="TEL-BESS-P-010",
        source_id="bess.fallback",
        logical_tick=10,
        sequence=1,
        subject_id="BESS",
        signal_id="active_power",
        value=0.4,
        unit=Unit.MEGAWATT,
        aggregation=AggregationKind.END,
        interval_start_tick=0,
        interval_end_tick=10,
        quality=quality,
        model_id="bess.fallback",
        model_version="1.0.0",
        topology_version=0,
    )
    alarm_state = AlarmStateV1(
        id="ALARM-STATE-001",
        source_id="alarm-service",
        logical_tick=80,
        sequence=1,
        condition_key="UNSUPPORTED_ISLAND_POWER_IMBALANCE",
        occurrence_id="OCC-001",
        subject_id="LOCAL",
        active=True,
        acknowledged=False,
        severity=AlarmSeverity.WARNING,
        active_since_tick=80,
        return_tick=None,
        acknowledge_tick=None,
        acknowledge_source_id=None,
        correlation_id="CMD-PCC-001",
    )
    alarm_event = AlarmEventV1(
        id="ALARM-EVENT-001",
        source_id="alarm-service",
        logical_tick=80,
        sequence=2,
        condition_key=alarm_state.condition_key,
        occurrence_id=alarm_state.occurrence_id,
        subject_id="LOCAL",
        transition=AlarmTransition.OCCURRED,
        active=True,
        acknowledged=False,
        severity=AlarmSeverity.WARNING,
        correlation_id="CMD-PCC-001",
        causation_id="TOPOLOGY-EVENT-001",
    )
    buses = (
        BusV1(id="GRID", is_infinite_source=True),
        BusV1(id="LOCAL"),
    )
    branch = BranchV1(
        id="PCC",
        from_bus_id="GRID",
        to_bus_id="LOCAL",
        requested_state=BranchState.CLOSED,
        actual_state=BranchState.CLOSED,
        state_sequence=0,
    )
    terminals = (
        TerminalV1(id="BESS-TERMINAL", asset_id="BESS", bus_id="LOCAL"),
        TerminalV1(id="GRID-SOURCE-TERMINAL", asset_id="GRID-SOURCE", bus_id="GRID"),
        TerminalV1(id="LOAD-TERMINAL", asset_id="LOAD", bus_id="LOCAL"),
    )
    component = ConnectedComponentV1(
        id="GRID+LOCAL@0",
        bus_ids=("GRID", "LOCAL"),
        contains_infinite_source=True,
        energization=EnergizationState.GRID_CONNECTED,
    )
    topology = TopologySnapshotV1(
        id="TOPOLOGY-000",
        source_id="topology-service",
        logical_tick=0,
        sequence=0,
        topology_version=0,
        buses=buses,
        branches=(branch,),
        terminals=terminals,
        components=(component,),
        quality=quality,
    )
    topology_event = TopologyEventV1(
        id="TOPOLOGY-EVENT-001",
        source_id="topology-service",
        logical_tick=80,
        sequence=1,
        branch_id="PCC",
        old_requested_state=BranchState.CLOSED,
        new_requested_state=BranchState.OPEN,
        old_actual_state=BranchState.CLOSED,
        new_actual_state=BranchState.OPEN,
        trigger_kind="COMMAND",
        correlation_id="CMD-PCC-001",
        causation_id="CMD-PCC-001",
        topology_version_before=0,
        topology_version_after=1,
        affected_component_ids=("GRID@1", "LOCAL@1"),
        energization=EnergizationState.ISLANDED_UNSUPPORTED,
    )
    balance = ActivePowerBalanceV1(
        logical_tick=10,
        load_mw=0.6,
        bess_ac_power_mw=0.4,
        grid_import_mw=0.2,
        island_imbalance_mw=None,
        energization=EnergizationState.GRID_CONNECTED,
        quality=quality,
    )
    source_counter = SourceCounterV1(source_id="scenario", value=1)
    handoff = ModelHandoffV1(
        asset_id="BESS",
        from_model_id="bess.fallback",
        from_model_version="1.0.0",
        to_model_id="bess.detailed",
        to_model_version="1.0.0",
        logical_tick=30,
        energy_stored_mwh=0.9999,
        energy_nominal_mwh=2.0,
        soc=0.49995,
        requested_power_mw=0.4,
        accepted_power_mw=0.4,
        applied_power_mw=0.4,
        operating_mode=OperatingMode.GRID_CONNECTED_AVAILABLE,
        energization=EnergizationState.GRID_CONNECTED,
        topology_version=0,
        component_id="GRID+LOCAL@0",
        quality=quality,
        last_command_id=command.id,
        source_sequences=(source_counter,),
    )
    fidelity_event = FidelityEventV1(
        id="FIDELITY-EVENT-001",
        source_id="model-registry",
        logical_tick=30,
        sequence=1,
        correlation_id="CMD-M-001",
        causation_id="CMD-M-001",
        result=FidelityResult.SUCCEEDED,
        handoff=handoff,
        energy_discontinuity_mwh=0.0,
        soc_discontinuity=0.0,
        power_discontinuity_mw=0.0,
        detail="fallback-to-detailed activation succeeded",
    )
    interlock_event = InterlockEventV1(
        id="INTERLOCK-EVENT-001",
        source_id="operating-context",
        logical_tick=80,
        sequence=1,
        target_id="BESS",
        reason=InterlockReason.UNSUPPORTED_ISLAND_SAFE_ZERO,
        previous_target_power_mw=-1.0,
        new_target_power_mw=0.0,
        previous_applied_power_mw=-0.5,
        new_applied_power_mw=0.0,
        energy_before_mwh=1.0,
        energy_after_mwh=1.0,
        correlation_id="CMD-PCC-001",
        causation_id="TOPOLOGY-EVENT-001",
        topology_version=1,
    )
    snapshot_event = SnapshotLifecycleEventV1(
        id="SNAPSHOT-EVENT-001",
        source_id="snapshot-service",
        logical_tick=90,
        sequence=1,
        snapshot_id="S-TT000-090",
        action=SnapshotAction.CAPTURED,
        correlation_id="CMD-SNAP-001",
        causation_id="CMD-SNAP-001",
        detail="snapshot captured",
    )
    publication = MacroPublicationV1(
        id="PUB-010",
        source_id="application",
        logical_tick=10,
        sequence=1,
        run_id="TT000-REF-V1",
        interval_start_tick=0,
        interval_end_tick=10,
        telemetry=(telemetry,),
        discrete_records=(acknowledgement,),
        energy_residual_mwh=0.0,
        coupling_residual_mwh=0.0,
    )
    configuration = SimulationConfigV1(
        base_tick_seconds=0.1,
        macro_ticks=10,
        energy_nominal_mwh=2.0,
        initial_soc=0.5,
        soc_min=0.1,
        soc_max=0.9,
        charge_limit_mw=1.0,
        discharge_limit_mw=1.0,
        charge_efficiency=0.95,
        discharge_efficiency=0.95,
        response_time_constant_seconds=2.0,
        ramp_up_mw_per_second=0.5,
        ramp_down_mw_per_second=0.5,
        load_mw=0.6,
        island_alarm_threshold_mw=0.05,
        seed=0,
    )
    scenario = ScenarioV1(
        id="TT000-REF",
        version="1.0.0",
        content_sha256="a" * 64,
        run_id="TT000-REF-V1",
        configuration=configuration,
        scheduled_commands=(command,),
    )
    trace_entry = TraceEntryV1(
        record_kind=TraceRecordKind.COMMAND,
        record_id=command.id,
        logical_tick=0,
        sequence=1,
        payload_schema_version="1.0.0",
        canonical_json='{"id":"CMD-P-001"}',
    )
    trace = TraceV1(run_id="TT000-REF-V1", parent_snapshot_id=None, entries=(trace_entry,))
    scheduled_event = ScheduledEventSnapshotV1(
        event_id="EVENT-CMD-P-001",
        logical_tick=10,
        phase=EventPhase.COMMAND,
        source_order=1,
        insertion_sequence=1,
        command=command,
        cancelled=False,
    )
    scheduler = SchedulerSnapshotV1(
        current_tick=0,
        current_phase=None,
        insertion_sequence=1,
        publication_sequence=0,
        source_counters=(source_counter,),
        pending_events=(scheduled_event,),
    )
    detailed_state = BessModelStateV1(
        model_id="bess.detailed",
        model_version="1.0.0",
        energy_stored_mwh=1.0,
        energy_nominal_mwh=2.0,
        requested_power_mw=0.4,
        accepted_power_mw=0.4,
        target_power_mw=0.4,
        applied_power_mw=0.4,
        operating_mode=OperatingMode.GRID_CONNECTED_AVAILABLE,
        response_state_mw=0.4,
        last_command_id=command.id,
    )
    fallback_state = BessModelStateV1(
        model_id="bess.fallback",
        model_version="1.0.0",
        energy_stored_mwh=1.0,
        energy_nominal_mwh=2.0,
        requested_power_mw=0.4,
        accepted_power_mw=0.4,
        target_power_mw=0.4,
        applied_power_mw=0.4,
        operating_mode=OperatingMode.GRID_CONNECTED_AVAILABLE,
        response_state_mw=None,
        last_command_id=command.id,
    )
    models = ModelRegistrySnapshotV1(
        active_model_id="bess.fallback",
        model_states=(detailed_state, fallback_state),
    )
    receipt = CommandReceiptV1(command=command, acknowledgement=acknowledgement, executed=True)
    controller = ControllerSnapshotV1(
        requested_power_mw=0.4,
        accepted_power_mw=0.4,
        target_power_mw=0.4,
        interlock_active=False,
        receipts=(receipt,),
        source_sequences=(source_counter,),
    )
    topology_runtime = TopologyRuntimeSnapshotV1(
        topology=topology,
        local_component_id="GRID+LOCAL@0",
        operating_mode=OperatingMode.GRID_CONNECTED_AVAILABLE,
        energization=EnergizationState.GRID_CONNECTED,
    )
    alarms = AlarmRuntimeSnapshotV1(states=(alarm_state,), next_occurrence_sequence=2)
    rng = RngSnapshotV1(
        algorithm="MT19937",
        state_version=3,
        state_values=(2147483648, 766982754, 497961170),
        gaussian_next=None,
    )
    snapshot = SnapshotEnvelopeV1(
        snapshot_id="S-TT000-090",
        logical_tick=90,
        phase=EventPhase.SNAPSHOT,
        run_id="TT000-REF-V1",
        parent_run_id=None,
        parent_snapshot_id=None,
        engine_name="energy-simlab",
        engine_version="1.0.0",
        engine_build="test-build",
        runtime_profile="cpython-3.14.7-windows-x86_64",
        compatibility_range="==1.0.0",
        scenario=scenario,
        configuration_sha256="b" * 64,
        contract_versions=("1.0.0",),
        scheduler=scheduler,
        models=models,
        controller=controller,
        topology=topology_runtime,
        alarms=alarms,
        rng=rng,
        pending_ingress=(),
        trace=trace,
        canonicalization_profile="python-json-v1",
        excluded_infrastructure_state=(
            "http_connections",
            "pacer_wall_clock",
            "viewer_state",
        ),
    )

    instances: tuple[VersionedV1, ...] = (
        quality,
        command,
        acknowledgement,
        telemetry,
        alarm_state,
        alarm_event,
        *buses,
        branch,
        *terminals,
        component,
        topology,
        topology_event,
        balance,
        source_counter,
        handoff,
        fidelity_event,
        interlock_event,
        snapshot_event,
        publication,
        configuration,
        scenario,
        trace_entry,
        trace,
        scheduled_event,
        scheduler,
        detailed_state,
        models,
        receipt,
        controller,
        topology_runtime,
        alarms,
        rng,
        snapshot,
    )
    by_type = {type(instance): instance for instance in instances}
    missing = set(V1_DOMAIN_TYPES) - set(by_type)
    if missing:
        raise AssertionError(f"sample registry is missing: {sorted(item.__name__ for item in missing)}")
    return tuple(by_type[domain_type] for domain_type in V1_DOMAIN_TYPES)
