"""Closed semantic enumerations for TT-000 contract version 1."""

from enum import StrEnum


class Unit(StrEnum):
    NONE = "1"
    BOOLEAN = "bool"
    COUNT = "count"
    MEGAWATT = "MW"
    MEGAWATT_HOUR = "MWh"
    PER_UNIT = "pu"
    SECOND = "s"


class CommandKind(StrEnum):
    SET_ACTIVE_POWER = "SET_ACTIVE_POWER"
    OPEN_PCC = "OPEN_PCC"
    ACTIVATE_DETAILED_MODEL = "ACTIVATE_DETAILED_MODEL"
    ACKNOWLEDGE_ALARM = "ACKNOWLEDGE_ALARM"
    CAPTURE_SNAPSHOT = "CAPTURE_SNAPSHOT"
    RESTORE_SNAPSHOT = "RESTORE_SNAPSHOT"
    PAUSE = "PAUSE"
    RESUME = "RESUME"


class CommandAuthority(StrEnum):
    INTERLOCK = "INTERLOCK"
    SCENARIO = "SCENARIO"
    OPERATOR = "OPERATOR"
    SUPERVISORY = "SUPERVISORY"


class AcknowledgementStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    ACCEPTED_WITH_LIMIT = "ACCEPTED_WITH_LIMIT"
    REJECTED = "REJECTED"
    DUPLICATE = "DUPLICATE"


class AcknowledgementReason(StrEnum):
    ACCEPTED = "ACCEPTED"
    ENERGY_FEASIBLE_LIMIT = "ENERGY_FEASIBLE_LIMIT"
    DUPLICATE = "DUPLICATE"
    EXPIRED = "EXPIRED"
    INVALID_SCHEMA = "INVALID_SCHEMA"
    INVALID_UNIT = "INVALID_UNIT"
    NAMEPLATE_LIMIT = "NAMEPLATE_LIMIT"
    STALE_SEQUENCE = "STALE_SEQUENCE"
    SUPERSEDED_BY_HIGHER_AUTHORITY = "SUPERSEDED_BY_HIGHER_AUTHORITY"
    TARGET_MODE_UNAVAILABLE = "TARGET_MODE_UNAVAILABLE"
    UNKNOWN_TARGET = "UNKNOWN_TARGET"
    VERSION_MISMATCH = "VERSION_MISMATCH"


class AggregationKind(StrEnum):
    END = "END"
    MEAN = "MEAN"
    INTEGRAL = "INTEGRAL"
    MIN = "MIN"
    MAX = "MAX"


class QualityValidity(StrEnum):
    GOOD = "GOOD"
    UNCERTAIN = "UNCERTAIN"
    BAD = "BAD"


class QualityReason(StrEnum):
    NORMAL = "NORMAL"
    SIMPLIFIED_ISLAND_PROXY = "SIMPLIFIED_ISLAND_PROXY"
    DEENERGIZED_OR_UNSUPPORTED = "DEENERGIZED_OR_UNSUPPORTED"
    STALE_OR_MODEL_ERROR = "STALE_OR_MODEL_ERROR"


class AlarmSeverity(StrEnum):
    WARNING = "WARNING"


class AlarmTransition(StrEnum):
    OCCURRED = "OCCURRED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RETURNED_TO_NORMAL = "RETURNED_TO_NORMAL"
    CLOSED = "CLOSED"


class BranchState(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class OperatingMode(StrEnum):
    OFF = "OFF"
    GRID_CONNECTED_AVAILABLE = "GRID_CONNECTED_AVAILABLE"
    ISLANDED_UNSUPPORTED = "ISLANDED_UNSUPPORTED"
    LIMITED = "LIMITED"
    TRIPPED = "TRIPPED"


class EnergizationState(StrEnum):
    GRID_CONNECTED = "GRID_CONNECTED"
    ISLANDED_UNSUPPORTED = "ISLANDED_UNSUPPORTED"
    DEENERGIZED = "DEENERGIZED"


class FidelityResult(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class SnapshotAction(StrEnum):
    CAPTURED = "CAPTURED"
    RESTORED = "RESTORED"
    REJECTED = "REJECTED"


class InterlockReason(StrEnum):
    UNSUPPORTED_ISLAND_SAFE_ZERO = "UNSUPPORTED_ISLAND_SAFE_ZERO"


class EventPhase(StrEnum):
    EXOGENOUS = "EXOGENOUS"
    TOPOLOGY = "TOPOLOGY"
    OPERATING_CONTEXT = "OPERATING_CONTEXT"
    FIDELITY = "FIDELITY"
    COMMAND = "COMMAND"
    CONTROL = "CONTROL"
    MODEL_ADVANCE = "MODEL_ADVANCE"
    AGGREGATION = "AGGREGATION"
    ALARM = "ALARM"
    PUBLICATION = "PUBLICATION"
    SNAPSHOT = "SNAPSHOT"


def event_phase_priority(phase: EventPhase) -> int:
    return (
        EventPhase.EXOGENOUS,
        EventPhase.TOPOLOGY,
        EventPhase.OPERATING_CONTEXT,
        EventPhase.FIDELITY,
        EventPhase.COMMAND,
        EventPhase.CONTROL,
        EventPhase.MODEL_ADVANCE,
        EventPhase.AGGREGATION,
        EventPhase.ALARM,
        EventPhase.PUBLICATION,
        EventPhase.SNAPSHOT,
    ).index(phase) * 10 + 10


class TraceRecordKind(StrEnum):
    COMMAND = "COMMAND"
    ACKNOWLEDGEMENT = "ACKNOWLEDGEMENT"
    TELEMETRY = "TELEMETRY"
    ALARM = "ALARM"
    TOPOLOGY = "TOPOLOGY"
    FIDELITY = "FIDELITY"
    PUBLICATION = "PUBLICATION"
    SNAPSHOT = "SNAPSHOT"
